### ISSUE TITLE
TypeError on auto-upload

### ISSUE THREAD

**Issue by rmay-intwine** [Flomp/wanderer#119]
Environment; docker installation of wanderer

When attempting to auto-upload gpx data I'm getting an Internal Error. The wanderer-web logs show the following exception
```
[INFO] [18:14:41]: Starting auto-upload
[INFO] [18:14:41]: Login successful. Cookie obtained.
TypeError: Request.formData: Could not parse content as FormData.
    at webidl.errors.exception (node:internal/deps/undici/undici:1801:14)
    at _Request.formData (node:internal/deps/undici/undici:5531:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PUT (file:///app/build/server/chunks/_server.ts-olSWK4FW.js:2992:18)
    at async render_endpoint (file:///app/build/server/index.js:1487:20)
    at async resolve2 (file:///app/build/server/index.js:4004:22)
    at async Object.handle (file:///app/build/server/chunks/hooks.server-49W1TjIe.js:59:20)
    at async respond (file:///app/build/server/index.js:3898:22)
    at async Array.ssr (file:///app/build/handler.js:1243:3)
[ERROR] [18:14:41]: Failed to upload file /app/uploads/20110520.gpx.
[INFO] [18:14:41]: Auto-upload completed
```
The gpx file is able to be uploaded using the create new trail UI element. I have seen this failure on every gpx file I've tried to auto-upload.

Here's the content of the auto created `data/uploads/` directory:
```
~/wanderer$ ls -lah data/uploads/
total 264K
drwxr-xr-x 2 root root  12K Nov  8 13:14 .
drwxr-xr-x 5 root root 4.0K Nov  8 11:22 ..
-rw-r--r-- 1 root root 246K Nov  8 13:14 20110520.gpx
```

I've added the requisite UPLOAD_USER and UPLOAD_PASSWORD to the docker-compose.yml file and the volume is left at the default

**Comment by Flomp** [comment]
Thanks for the hint. Fixed in v0.10.1.

**Comment by rmay-intwine** [comment]
Upgraded to 0.10.1 and verified fix.  Thanks :)
