### ISSUE TITLE
Import of tracks with unicode characters in filenames always fail

### ISSUE THREAD

**Issue by 2600box** [Flomp/wanderer#122]
Hello,

I am new user of Wanderer in docker with version v0.10.1.

Importing tracks from files that have unicode characters always fails with a brief pop-up message in the GUI and the below log. Renaming the file to remove unicode characters solves the problem.

You can see below where the import fails with original filename: `côté d'ivoire.kml` but succeeds when renamed to `cote_divoire.kml`

```
wanderer-web     | Error: aborted
wanderer-web     |     at connResetException (node:internal/errors:720:14)
wanderer-web     |     at abortIncoming (node:_http_server:781:17)
wanderer-web     |     at socketOnClose (node:_http_server:775:3)
wanderer-web     |     at Socket.emit (node:events:529:35)
wanderer-web     |     at TCP.<anonymous> (node:net:350:12) {
wanderer-web     |   code: 'ECONNRESET'
wanderer-web     | }
wanderer-web     | Error: HTTP error status codes must be between 400 and 599 — undefined is invalid
wanderer-web     |     at error (file:///app/build/server/chunks/index-oXbhYwP7.js:54:11)
wanderer-web     |     at PUT (file:///app/build/server/chunks/_server.ts-Ax65YgaW.js:3044:11)
wanderer-web     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wanderer-web     |     at async render_endpoint (file:///app/build/server/index.js:1487:20)
wanderer-web     |     at async resolve2 (file:///app/build/server/index.js:4004:22)
wanderer-web     |     at async auth (file:///app/build/server/chunks/hooks.server-248u8dmy.js:118:20)
wanderer-web     |     at async respond (file:///app/build/server/index.js:3898:22)
wanderer-web     |     at async Array.ssr (file:///app/build/handler.js:1243:3)
wanderer-search  | [2024-11-09T20:54:55Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000127
wanderer-search  | [2024-11-09T20:55:10Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000348
wanderer-web     | Error: aborted
wanderer-web     |     at connResetException (node:internal/errors:720:14)
wanderer-web     |     at abortIncoming (node:_http_server:781:17)
wanderer-web     |     at socketOnClose (node:_http_server:775:3)
wanderer-web     |     at Socket.emit (node:events:529:35)
wanderer-web     |     at TCP.<anonymous> (node:net:350:12) {
wanderer-web     |   code: 'ECONNRESET'
wanderer-web     | }
wanderer-web     | Error: HTTP error status codes must be between 400 and 599 — undefined is invalid
wanderer-web     |     at error (file:///app/build/server/chunks/index-oXbhYwP7.js:54:11)
wanderer-web     |     at PUT (file:///app/build/server/chunks/_server.ts-Ax65YgaW.js:3044:11)
wanderer-web     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wanderer-web     |     at async render_endpoint (file:///app/build/server/index.js:1487:20)
wanderer-web     |     at async resolve2 (file:///app/build/server/index.js:4004:22)
wanderer-web     |     at async auth (file:///app/build/server/chunks/hooks.server-248u8dmy.js:118:20)
wanderer-web     |     at async respond (file:///app/build/server/index.js:3898:22)
wanderer-web     |     at async Array.ssr (file:///app/build/handler.js:1243:3)
wanderer-search  | [2024-11-09T20:55:25Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000091
wanderer-search  | [2024-11-09T20:55:40Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000188
wanderer-web     | Error: aborted
wanderer-web     |     at connResetException (node:internal/errors:720:14)
wanderer-web     |     at abortIncoming (node:_http_server:781:17)
wanderer-web     |     at socketOnClose (node:_http_server:775:3)
wanderer-web     |     at Socket.emit (node:events:529:35)
wanderer-web     |     at TCP.<anonymous> (node:net:350:12) {
wanderer-web     |   code: 'ECONNRESET'
wanderer-web     | }
wanderer-web     | Error: HTTP error status codes must be between 400 and 599 — undefined is invalid
wanderer-web     |     at error (file:///app/build/server/chunks/index-oXbhYwP7.js:54:11)
wanderer-web     |     at PUT (file:///app/build/server/chunks/_server.ts-Ax65YgaW.js:3044:11)
wanderer-web     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
wanderer-web     |     at async render_endpoint (file:///app/build/server/index.js:1487:20)
wanderer-web     |     at async resolve2 (file:///app/build/server/index.js:4004:22)
wanderer-web     |     at async auth (file:///app/build/server/chunks/hooks.server-248u8dmy.js:118:20)
wanderer-web     |     at async respond (file:///app/build/server/index.js:3898:22)
wanderer-web     |     at async Array.ssr (file:///app/build/handler.js:1243:3)
wanderer-search  | [2024-11-09T20:55:56Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000230
wanderer-search  | [2024-11-09T20:56:11Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000100
wanderer-search  | [2024-11-09T20:56:26Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000099
wanderer-search  | [2024-11-09T20:56:41Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000063
wanderer-search  | [2024-11-09T20:56:56Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000102
wanderer-search  | [2024-11-09T20:57:11Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000088
wanderer-search  | [2024-11-09T20:57:26Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000158
wanderer-search  | [2024-11-09T20:57:41Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000071
wanderer-search  | [2024-11-09T20:57:56Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000075
wanderer-search  | [2024-11-09T20:58:12Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000092
wanderer-search  | [2024-11-09T20:58:23Z INFO  actix_web::middleware::logger] 10.10.12.3 "POST /indexes/trails/documents HTTP/1.1" 202 134 "-" "Meilisearch Go (v0.26.2)" 0.033128
wanderer-search  | [2024-11-09T20:58:23Z INFO  actix_web::middleware::logger] 10.10.12.3 "PUT /indexes/trails/documents HTTP/1.1" 202 136 "-" "Meilisearch Go (v0.26.2)" 0.025443
wanderer-search  | [2024-11-09T20:58:23Z INFO  index_scheduler::batch] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 336 }
wanderer-search  | [2024-11-09T20:58:23Z INFO  index_scheduler] A batch of tasks was successfully completed.
wanderer-search  | [2024-11-09T20:58:23Z INFO  index_scheduler::batch] document addition done: DocumentAdditionResult { indexed_documents: 1, number_of_documents: 336 }
wanderer-search  | [2024-11-09T20:58:23Z INFO  index_scheduler] A batch of tasks was successfully completed.
wanderer-search  | [2024-11-09T20:58:27Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /health HTTP/1.1" 200 22 "-" "curl/8.5.0" 0.000105
```

**Comment by 2600box** [comment]
Weird. They are importing correctly now...

Though there is no filter of duplicates, so I will try to remove all my tracks and start fresh.
