### ISSUE TITLE
Somehow lost a track

### ISSUE THREAD

**Issue by thomas-mc-work** [Flomp/wanderer#136]
Hello,

somehow a track in my collection got kind of lost. Whats weird about it is that I can see it on the view and in the lists view. The map draws the route correctly and the preview picture is also shown. But when I select it or try to edit then I get a `404 Not Found`. The target URL is like `http://wanderer.lan/trail/view/3mqapl9vnxe2haz`.

How could that happen?

Is there anything I can do to track that down?

**Comment by thomas-mc-work** [comment]
It is existing in the `trails` table in the database:

![image](https://github.com/user-attachments/assets/b4cba88e-f4e0-43ff-b22f-9a05f930d7f0)

**Comment by thomas-mc-work** [comment]
… and the query seems to reach the database:

![image](https://github.com/user-attachments/assets/3914ff2e-bf18-4b1c-a075-21f0b6498cd7)

Not sure about the meaning of the first line though. I'm not accessing the site as an anonymous user.

**Comment by Flomp** [comment]
Hi there,

that sounds a bit like #133. So the trail is there in the overview (`/trails`), but `/trail/view/3mqapl9vnxe2haz` throws a 404?

Can you see any logs in the wanderer-web container? Or is there any other 404 error in PocketBase?

**Comment by thomas-mc-work** [comment]
> that sounds a bit like #133.

Might be, but there are differences. I don't think that I've set my track to public before. And then I've created a public track to test that and it is working – opposed to the issue description.

> Can you see any logs in the wanderer-web container?

I get this error upon the request:

    ClientResponseError 404: Missing required record id.
        at RecordService.getOne (file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:8581)
        at RecordService.getOne (file:///app/node_modules/pocketbase/dist/pocketbase.es.mjs:1:19801)
        at GET (file:///app/build/server/chunks/_server.ts-89kunyrk.js:22:66)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async render_endpoint (file:///app/build/server/index.js:1487:20)
        at async resolve2 (file:///app/build/server/index.js:4004:22)
        at async auth (file:///app/build/server/chunks/hooks.server-248u8dmy.js:118:20)
        at async respond (file:///app/build/server/index.js:3898:22)
        at async Array.ssr (file:///app/build/handler.js:1243:3) {
      url: 'http://db:8090/api/collections/users_anonymous/records/',
      status: 404,
      response: { code: 404, message: 'Missing required record id.', data: {} },
      isAbort: false,
      originalError: {
        url: 'http://db:8090/api/collections/users_anonymous/records/',
        status: 404,
        response: { code: 404, message: 'Missing required record id.', data: {} }
      }
    }

> Or is there any other 404 error in PocketBase?

Neither in the conatiner log nor in the Pocketbase logs.

**Comment by Flomp** [comment]
Ah thanks, very helpful! I found the issue:
Since v0.11.0 summit logs have an author. However, previously they did not. So summit logs created before v0.11.0 will break this call because p.author will be `null`:
https://github.com/Flomp/wanderer/blob/c42ca754df7962a7be34d60953ba510ddb682c09/web/src/routes/api/v1/trail/%5Bid%5D/%2Bserver.ts#L28

Could you please test this theory by adding an author to the summit log attached to your trail in PocketBase? 
Go to the trails table -> remember the id in the summit log column -> go the summit log table -> find the respective row -> click -> add author

Thanks!

**Comment by thomas-mc-work** [comment]
> Go to the trails table -> remember the id in the summit log column -> go the summit log table -> find the respective row -> click -> add author

:tada: Bingo! Thank you very much!
