### ISSUE TITLE
Meilisearch rejects gpx file due to size

### ISSUE THREAD

**Issue by garbast** [Flomp/wanderer#4]
I have a gpx file that is 528,6 kB large. When i try to upload it, i get the following error:

Rename to .gpx without .txt to test with.
[2021-10-24_536064034_Essen-Mitte nach Bochum-Hauptbahnhof.gpx.txt](https://github.com/Flomp/wanderer/files/14627011/2021-10-24_536064034_Essen-Mitte.nach.Bochum-Hauptbahnhof.gpx.txt)

```
web-1     |     at get_raw_body (file:///app/build/handler.js:973:9)
web-1     |     at getRequest (file:///app/build/handler.js:1052:7)
web-1     |     at Array.ssr (file:///app/build/handler.js:1230:19)
web-1     |     at handle (file:///app/build/handler.js:1300:23)
web-1     |     at file:///app/build/handler.js:1300:40
web-1     |     at Array.<anonymous> (file:///app/build/handler.js:1219:4) {
web-1     |   status: 413,
web-1     |   text: 'Payload Too Large'
web-1     | }
web-1     | SvelteKitError: Content-length of 528846 exceeds limit of 524288 bytes.
web-1     |     at Object.start (file:///app/build/handler.js:984:19)
web-1     |     at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2333:23)
web-1     |     at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2366:3)
web-1     |     at new ReadableStream (node:internal/webstreams/readablestream:289:7)
web-1     |     at get_raw_body (file:///app/build/handler.js:973:9)
web-1     |     at getRequest (file:///app/build/handler.js:1052:7)
web-1     |     at Array.ssr (file:///app/build/handler.js:1230:19)
web-1     |     at handle (file:///app/build/handler.js:1300:23)
web-1     |     at file:///app/build/handler.js:1300:40
web-1     |     at Array.<anonymous> (file:///app/build/handler.js:1219:4) {
web-1     |   status: 413,
web-1     |   text: 'Payload Too Large'
web-1     | }
web-1     | SvelteKitError: Content-length of 528846 exceeds limit of 524288 bytes.
web-1     |     at Object.start (file:///app/build/handler.js:984:19)
web-1     |     at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2333:23)
web-1     |     at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2366:3)
web-1     |     at new ReadableStream (node:internal/webstreams/readablestream:289:7)
web-1     |     at get_raw_body (file:///app/build/handler.js:973:9)
web-1     |     at getRequest (file:///app/build/handler.js:1052:7)
web-1     |     at Array.ssr (file:///app/build/handler.js:1230:19)
web-1     |     at handle (file:///app/build/handler.js:1300:23)
web-1     |     at file:///app/build/handler.js:1300:40
web-1     |     at Array.<anonymous> (file:///app/build/handler.js:1219:4) {
web-1     |   status: 413,
web-1     |   text: 'Payload Too Large'
web-1     | }
```

**Comment by Flomp** [comment]
Turns out SvelteKit has a body size limit that I didn't know about: 
https://kit.svelte.dev/docs/adapter-node#environment-variables-bodysizelimit

You should be able to add a 
`BODY_SIZE_LIMIT: Infinity`
to the environment section of the wanderer-web section in your docker-compose.yml.

I'm currently not at my computer to test it. I'll add it to the docs later tonight if it works.

Thanks for testing!

**Comment by garbast** [comment]
With the env parameter set i still get an error

```
{
    "url": "http://db:8090/api/collections/trails/records/4skbnicy838t48a",
    "status": 400,
    "response": {
        "code": 400,
        "message": "Something went wrong while processing your request.",
        "data": {
            "photos": {
                "code": "validation_file_size_limit",
                "message": "Failed to upload \"20240309_143022.jpg\" - the maximum allowed file size is 5242880 bytes."
            }
        }
    },
    "isAbort": false,
    "originalError": {
        "url": "http://db:8090/api/collections/trails/records/4skbnicy838t48a",
        "status": 400,
        "data": {
            "code": 400,
            "message": "Something went wrong while processing your request.",
            "data": {
                "photos": {
                    "code": "validation_file_size_limit",
                    "message": "Failed to upload \"20240309_143022.jpg\" - the maximum allowed file size is 5242880 bytes."
                }
            }
        }
    },
    "name": "ClientResponseError 400"
}
```

![image](https://github.com/Flomp/wanderer/assets/5036924/83e53a78-bb11-4ab1-96ee-47e6e48f18f4)

**Comment by garbast** [comment]
Updated to latest version and executed a shell in the web container. There i have these env variables present:
```
UPLOAD_PASSWORD=
PUBLIC_DISABLE_SIGNUP=true
NODE_VERSION=18.20.1
HOSTNAME=28cc2c31f9cb
ORIGIN=http://localhost:3000
YARN_VERSION=1.22.19
UPLOAD_USER=
SHLVL=2
HOME=/root
PUBLIC_POCKETBASE_URL=http://db:8090
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BODY_SIZE_LIMIT=Infinity
MEILI_MASTER_KEY=<replaced>
MEILI_URL=http://search:7700
PWD=/app
NODE_ENV=production
```
But still the upload failes with the error validation_file_size_limit. Where does the BODY_SIZE_LIMIT need to be set in the docker-compose.yaml?

**Comment by Flomp** [comment]
Ah, I see what's happening. The good news is you solved the frontend file size issue. The bad news is you are running into the backend file size limit. Currently, uploads are capped at 5MB for both photos and gpx files in PocketBase.
![image psd](https://github.com/Flomp/wanderer/assets/26000991/07911378-833a-49ea-ad8b-8f589ae0198e)

You can adapt the limit by making the PocketBase container publically available and navigating to the PocketBase admin panel at http://<your_pocketbase_url>:8090/_/. From there you can edit the respective fields in the trails collection to increase the file size. 

Unfortunately, I currently cannot find a way to make this limit into an environment variable without rewriting a considerable amount of PocketBase's code. So I'm not sure if the update will stick when you update the wanderer-db container.

**Comment by garbast** [comment]
For now i wouldnt go so fare to modify PocketBase. That's something for Version 2.x ;)

But this is the ideal moment for me to suggest some paradigm change. Would it hurt to much to store images and gpx files individually in the file system? 

This would have the benefit, that the database would not get out of hand. Imagine you have 200 trails after some years and have added a lot of images too. Then every backup would be very large because all of the images get backuped again and again.
Having the images separate, they only get backuped once.

**Comment by Flomp** [comment]
I politely disagree with the suggested paradigm change. PocketBase stores the database and the stored data separately. You can check that for yourself: in your `pb_data` folder you will find a `data.db` file containing the database and a storage folder with your gpx files and images. Consequently, it is easy to backup the data separately from the database. Incremental backups should also be unproblematic as the data in the storage folder does not change even if the associated record in the database is updated (unless you swap the file, of course).

**Comment by garbast** [comment]
I'm sorry. I was wrong. Didn't knew that PocketBase is storing files like that. So this is sorted but the upload limit problem remains and needs to be fixed on a later day.

**Comment by garbast** [comment]
I would like to comeback to this topic. Would it be a solution to increase the gpx and photos field max file size via a migration?

The field was created with
- https://github.com/Flomp/wanderer/blob/1a236968809a40f1027278db7e68de90813b312c/db/migrations/1709593298_collections_snapshot.go#L284
- https://github.com/Flomp/wanderer/blob/1a236968809a40f1027278db7e68de90813b312c/db/migrations/1709593298_collections_snapshot.go#L300

So i guess it could be possible to migrate it to 500mb with this?
```
edit_photos := &schema.SchemaField{}
json.Unmarshal([]byte(`{
      "system": false,
      "id": "aqbpyawe",
      "name": "photos",
      "type": "file",
      "required": false,
      "presentable": false,
      "unique": false,
      "options": {
	      "mimeTypes": [
		      "image/jpeg",
		      "image/vnd.mozilla.apng",
		      "image/png",
		      "image/webp",
		      "image/svg+xml"
	      ],
	      "thumbs": [],
	      "maxSelect": 99,
	      "maxSize": 524288000,
	      "protected": false
      }
}`), edit_photos)
collection.Schema.AddField(edit_photos)

edit_gpx := &schema.SchemaField{}
json.Unmarshal([]byte(`{
        "system": false,
        "id": "k8xdrsyv",
        "name": "gpx",
        "type": "file",
        "required": false,
        "presentable": false,
        "unique": false,
        "options": {
	        "mimeTypes": [],
	        "thumbs": [],
	        "maxSelect": 1,
	        "maxSize": 524288000,
	        "protected": false
        }
}`), edit_gpx)
collection.Schema.AddField(edit_gpx)
```

**Comment by Flomp** [comment]
It is absolutely not a problem to increase the max file size in pocketbase. However, I consider 5MB to be a reasonable size for most photos. In case you would like to increase the limit in your installation you can do so fairly easily. Either with your own migration or by accessing the pocketbase admin panel:
[https://wanderer.to/guides/custom-categories/#backend-access](https://wanderer.to/guides/custom-categories/#backend-access)

**Comment by SergNif** [comment]
I get this message error too. I`m try load image 2,7 Mb. 
Solve. Work for me/.
after building project as ' pnpm dev build '
1.   I`m open file path_to_project / build / handler.js
2. find string '  const body_size_limit = parse_body_size_limit(env('BODY_SIZE_LIMIT', '512K')); '
3. change 512K to 50M  -> it's limit load 50 megabytes
4. save file.
It`s all -> enjoy \_0_/
