### ISSUE TITLE
error "Payload Too Large"

### ISSUE THREAD

**Issue by 4ndreasH** [Flomp/wanderer#49]
Thank you very much for this great app!

I can upload small gpx files but most of my files are some MB big and with these I get an error:

```
SvelteKitError: Content-length of 965006 exceeds limit of 524288 bytes.
    at Object.start (file:///app/build/handler.js:984:19)
    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2333:23)
    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2366:3)
    at new ReadableStream (node:internal/webstreams/readablestream:289:7)
    at get_raw_body (file:///app/build/handler.js:973:9)
    at getRequest (file:///app/build/handler.js:1052:7)
    at Array.ssr (file:///app/build/handler.js:1230:19)
    at handle (file:///app/build/handler.js:1300:23)
    at file:///app/build/handler.js:1300:40
    at Array.<anonymous> (file:///app/build/handler.js:1219:4) {
  status: 413,
  text: 'Payload Too Large'
}

```
On upload the map shows the correct route. "Route speichern" then gives "Error saving trail.". The new entry is listed under tracks but the map is without a route.

A similar problem occurs when uploading photos that are bigger then ~800x600px. 

Andreas

(linux docker 26.0.0, wanderer v0.3.2)

**Comment by 4ndreasH** [comment]
sorry, this is a duplicate of [https://github.com/Flomp/wanderer/issues/4](https://github.com/Flomp/wanderer/issues/4)
The fix (BODY_SIZE_LIMIT: Infinity) works for me.
