### ISSUE TITLE
Uploading larger images lead to error

### ISSUE THREAD

**Issue by garbast** [Flomp/wanderer#6]
When i want to upload a larger image with 7.1 MB i get an error:

```
web-1     | SvelteKitError: Content-length of 7088136 exceeds limit of 524288 bytes.
web-1     |     at Object.start (file:///app/build/handler.js:984:19)
web-1     |     at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2333:23)
web-1     |     at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2366:3)
web-1     |     at new ReadableStream (node:internal/webstreams/readablestream:289:7)
web-1     |     at get_raw_body (file:///app/build/handler.js:973:9)
web-1     |     at getRequest (file:///app/build/handler.js:1052:7)
web-1     |     at Array.ssr (file:///app/build/handler.js:1230:19)
web-1     |     at handle (file:///app/build/handler.js:1300:23)
web-1     |     at file:///app/build/handler.js:1300:40
web-1     |     at Array.<anonymous> (file:///app/build/handler.js:1219:4) {
web-1     |   status: 413,
web-1     |   text: 'Payload Too Large'
web-1     | }
```

**Comment by Flomp** [comment]
Please refer to [#4](https://github.com/Flomp/wanderer/issues/4).
